name: Print PR context
on:
  push:
  workflow-dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github.event) }}"